name: emu-post
channels:
    - plotly
    - conda-forge
    - defaults
dependencies:
    - python=3.7
    - mayavi=4.7.1
    - numpy
    - h5py
    - plotly
    - chart-studio
    - matplotlib
    - gooey
